# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.define "debian_bookworm" do |debian_bookworm| 

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
    debian_bookworm.vm.box = "debian/bookworm64"

    # config.ssh.insert_key = false

    debian_bookworm.vm.provision :ansible_local do |ansible|
      ansible.playbook = "ansible/setup.yml"
      ansible.inventory_path = "ansible/hosts.yml"
    end

    debian_bookworm.vm.provider "virtualbox" do |v|
      # Minimal resources needed for Minikube are 2 CPU cores and 2GB of memory
      v.memory = 4096
      v.cpus = 4
    end
  end
end
