# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.define "debian_bookworm" do |debian_bookworm| 
    debian_bookworm.vm.box = "debian/bookworm64"
    debian_bookworm.vm.version = "12.20250126.1"

    debian_bookworm.vm.provision :ansible_local do |ansible|
      ansible.playbook = "ansible/setup.yml"
    end

    debian_bookworm.vm.provider "virtualbox" do |v|
      # Minimal resources needed for Minikube are 2 CPU cores and 2GB of memory
      v.memory = 4096
      v.cpus = 4
    end
  end
end
